### AUTH APIs

# Register Organisation + Admin
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "orgName": "PrasannaOrg",
  "adminName": "Prasanna Admin",
  "email": "admin@prasannaorg.com",
  "password": "Prasanna123"
}

###

# Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin1@basanttech.com",
  "password": "Password123"
}

###

### EMPLOYEE APIs

# List all employees
GET http://localhost:5000/api/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ2FuaXNhdGlvbklkIjoxLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzY0MjIzMTA5LCJleHAiOjE3NjQyNTE5MDl9.xW3L7phvnOKygREpf3cIW7bQ3hXg9L41C7gl3eFGlZU

###

# Get employee by ID
GET http://localhost:5000/api/employees/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ2FuaXNhdGlvbklkIjoxLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzY0MjIzMTA5LCJleHAiOjE3NjQyNTE5MDl9.xW3L7phvnOKygREpf3cIW7bQ3hXg9L41C7gl3eFGlZU

###

# Create employee
POST http://localhost:5000/api/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ2FuaXNhdGlvbklkIjoxLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzY0MjIzMTA5LCJleHAiOjE3NjQyNTE5MDl9.xW3L7phvnOKygREpf3cIW7bQ3hXg9L41C7gl3eFGlZU
Content-Type: application/json

{
  "firstName": "Sunil",
  "lastName": "Kumar",
  "email": "sunilkumar@prasannaorg.com",
  "phone": "01234567890"
}

###

# Update employee
PUT http://localhost:5000/api/employees/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ2FuaXNhdGlvbklkIjoxLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzY0MjIzMTA5LCJleHAiOjE3NjQyNTE5MDl9.xW3L7phvnOKygREpf3cIW7bQ3hXg9L41C7gl3eFGlZU
Content-Type: application/json

{
  "phone": "7418529630"
}

###

# Delete employee
DELETE http://localhost:5000/api/employees/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ2FuaXNhdGlvbklkIjoxLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzY0MjIzMTA5LCJleHAiOjE3NjQyNTE5MDl9.xW3L7phvnOKygREpf3cIW7bQ3hXg9L41C7gl3eFGlZU
###

### TEAM APIs

# List all teams
GET http://localhost:5000/api/teams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ2FuaXNhdGlvbklkIjoxLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzY0MjIzMTA5LCJleHAiOjE3NjQyNTE5MDl9.xW3L7phvnOKygREpf3cIW7bQ3hXg9L41C7gl3eFGlZU
###

# Get team by ID
GET http://localhost:5000/api/teams/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ2FuaXNhdGlvbklkIjoxLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzY0MjIzMTA5LCJleHAiOjE3NjQyNTE5MDl9.xW3L7phvnOKygREpf3cIW7bQ3hXg9L41C7gl3eFGlZU

###

# Create team
POST http://localhost:5000/api/teams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ2FuaXNhdGlvbklkIjoxLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzY0MjIzMTA5LCJleHAiOjE3NjQyNTE5MDl9.xW3L7phvnOKygREpf3cIW7bQ3hXg9L41C7gl3eFGlZU
Content-Type: application/json

{
  "name": "HR Department",
  "description": "HR Team should maintain the responsibilites of the company"
}

###

# Update team
PUT http://localhost:5000/api/teams/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ2FuaXNhdGlvbklkIjoxLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzY0MjIzMTA5LCJleHAiOjE3NjQyNTE5MDl9.xW3L7phvnOKygREpf3cIW7bQ3hXg9L41C7gl3eFGlZU
Content-Type: application/json

{
  "description": "HR Team should maintain the data of Employees"
}

###

# Delete team
DELETE http://localhost:5000/api/teams/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ2FuaXNhdGlvbklkIjoxLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzY0MjIzMTA5LCJleHAiOjE3NjQyNTE5MDl9.xW3L7phvnOKygREpf3cIW7bQ3hXg9L41C7gl3eFGlZU

###

### TEAM ASSIGNMENT APIs

# Assign multiple employees to a team
POST http://localhost:5000/api/teams/2/assign
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ2FuaXNhdGlvbklkIjoxLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzY0MjIzMTA5LCJleHAiOjE3NjQyNTE5MDl9.xW3L7phvnOKygREpf3cIW7bQ3hXg9L41C7gl3eFGlZU
Content-Type: application/json

{
  "employeeIds": [1,2,3]
}

###

# Assign single employee to a team
POST http://localhost:5000/api/teams/2/assign
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ2FuaXNhdGlvbklkIjoxLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzY0MjIzMTA5LCJleHAiOjE3NjQyNTE5MDl9.xW3L7phvnOKygREpf3cIW7bQ3hXg9L41C7gl3eFGlZU
Content-Type: application/json

{
  "employeeId": 3
}

###

# Unassign employee from a team
DELETE http://localhost:5000/api/teams/2/unassign
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ2FuaXNhdGlvbklkIjoxLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzY0MjIzMTA5LCJleHAiOjE3NjQyNTE5MDl9.xW3L7phvnOKygREpf3cIW7bQ3hXg9L41C7gl3eFGlZU
Content-Type: application/json

{
  "employeeId": 2
}

### Get Logs (Admins Only)
GET http://localhost:5000/api/logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ2FuaXNhdGlvbklkIjoxLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzY0MjIzMTA5LCJleHAiOjE3NjQyNTE5MDl9.xW3L7phvnOKygREpf3cIW7bQ3hXg9L41C7gl3eFGlZU
Accept: application/json

### Get Stats Summary
GET http://localhost:5000/api/stats/summary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm9yZ2FuaXNhdGlvbklkIjoxLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzY0MjIzMTA5LCJleHAiOjE3NjQyNTE5MDl9.xW3L7phvnOKygREpf3cIW7bQ3hXg9L41C7gl3eFGlZU
